### PR TITLE
Switch to Dynamic Frameworks

### LINKED ISSUE #62: Switch to frameworks
Now that Apple has embraced frameworks on iOS, MMMarkdown can move to a framework on both platforms.

### PR DESCRIPTION
**Pull request by mdiep**
Fixes #62

### CODE REVIEW

**Comment by mdiep** [comment]
@maddox Do you want to see if this iOS framework works for you?

**Comment by maddox** [comment]
oooh, yeah I'll give it a go tonight.

**Comment by maddox** [comment]
lol sorry

**Comment by mdiep** [comment]
:smile:

**Pull request merged**
